### PR TITLE
Closes softlayer/ember-style-guide#24

### PR DESCRIPTION
**Pull request by notmessenger**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/ember-style-guide/45)

### CODE REVIEW

**Comment by erangeles** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/ember-style-guide/45)

**Comment by jonathandavidson** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/ember-style-guide/45)

**Comment by theoshu** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/ember-style-guide/45)

**Comment by joshforisha** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/ember-style-guide/45)

**Pull request merged**
